### ISSUE TITLE
When updating the SW, what's the case for listening to events other than 'waiting'?

### ISSUE THREAD

**Issue by guytepper** [jakearchibald/wittr#11]
Hi @jakearchibald, thanks for the great tutorial! :)

I was wondering why there's a need to listen to the [`statechange` & `installing` events](https://github.com/jakearchibald/wittr/compare/task-update-notify...update-interaction), if (correct me if I'm wrong) in both cases the service worker would be  `waiting` eventually.

**Comment by jakearchibald** [comment]
Wow, sorry for missing this question! Because you can't predict what state the worker will be in when the code on your page loads, you need to cater for a new worker being in any of the states prior to "installed".
