### ISSUE TITLE
Suggestion: add required eslint dependencies to package.json

### ISSUE THREAD

**Issue by icflorescu** [jakearchibald/wittr#16]
Hi @jakearchibald, I noticed there's an `.eslint` config file in the root of the project, and that's a good thing, because most contemporary editors (i.e. Atom, VSCode) are able to pick it up and lint "on the fly". However, a commonly accepted best-practice is to add the required `devDependencies` - in this case `eslint` and the `babel-eslint` parser to the project's `package.json`:

    npm i -D eslint babel-eslint

**Comment by icflorescu** [comment]
I'm aware that updating all branches would involve quite a bit of work, so I'm willing to issue a PR. Are you interested?

**Comment by apieceofbart** [comment]
great point!

**Comment by jakearchibald** [comment]
Send me a PR for master, I'll take care of the branches, thanks!

**Comment by jakearchibald** [comment]
Merged!
