### ISSUE TITLE
 fatal error LNK1107: invalid or corrupt file: cannot read at 0x21E00D

### ISSUE THREAD

**Issue by sage94** [jakearchibald/wittr#27]
Hello, please am still a newbie at node,though I have done a couple of projects, with it. I bumped into your amazing tutorial but each time I try running the `npm install` on your app, this particular error stops the app from installing.
`fatal error LNK1107: invalid or corrupt file: cannot read at 0x21E00D`
I don't really know what is wrong. Please can you assist me.
Node Version: 8.6.0
Node gyp Version: 3.6.3
npm Version: 5.5.1

**Comment by engbishoy14** [comment]
this post copied

Hello everyone,
I hope this post will solve all the problems that you are facing right now. (Windows users)
Here are some simple instructions to make everything works without any problems.

install the latest nodejs from https://nodejs.org/en/12.
choose LTS version which is the recommended for most users.
install it.
1- go to your CMD (command line) and run it as administrator.
2- write this command to make sure that nodejs is working probably node -v
3- this will give you the current version number of the installed nodeje which is suppose to be in this format vX.X.X (in my case it was v8.9.0)
4- optional step
5- write in the CMD node it will wait a second then show you this> now write any mathematical question like 5+5 and it will print the result that will also mean that nodejs is installed and working correctly.
run the following command npm install --global --production windows-build-tools which will install all the required programs (be patient as it will take a while) you have to be in administrator mode in order for this command to work correctly.
1- Now this command will install Python 2.X (2.7 in my case) which requires you do add something in the windows environmental variables
2- in the path variable you will add the location of python installation (by default: C:\Python27 where c is the directory where the operating system is installed) also add this path even if it doesn’t exist (C:\Python27\Scripts) it may vary based on the installation location.
Now. Nodejs and npm are installed and configured correctly. But if there were any issues it will probably be one of the following
1- missing programs and compilers for Nodejs to run correctly
2- like .NET Framework and c++ redistributable they are required so do install both
3- c++ redistributable => http://www.standaloneofflineinstallers.com/2015/12/Microsoft-Visual-C-Redistributable-2015-2013-2012-2010-2008-2005-32-bit-x86-64-bit-x64-Standalone-Offline-Installer-for-Windows.html9
4- .NET Framework => https://www.microsoft.com/en-us/download/search.aspx?q=.net%20framework6
Now back the Google challenge App
install the following program for sass called Ruby => https://rubyinstaller.org/15
in the CMD run the following command npm install gulp-sass -g
1- this will install gulp which is required for sass
then install git bash => https://git-scm.com/downloads/2
1- using it’s CMD run the following command git clone https://github.com/jakearchibald/wittr
2- by default this will download the project to the following directory (C:\Users\<computer user name>\wittr)
now in the windows CMD go to this directory
run this command npm install. This should run without any problems
then run npm run serve which will run the app`
If for any reason you are still getting some issues or problems. Please post them here and mention me and I will do my best to help you out solve this issue so we can start the course

**Comment by jakearchibald** [comment]
@sage94 did the above work for you?

**Comment by sage94** [comment]
Yes, it worked, I compiled and installed the app.
Thanks alot @engbishoy14. I am very grateful

**Comment by ramankarman** [comment]
I also found helpful [this comment](https://github.com/nwjs/nw-gyp/issues/63#issuecomment-77660581). After installing Python 2.7 and Visual C++ Build Tools I deleted node_modules folder, opened CMD from Administrator and ran `npm install --msvs_version=2015`. Aaand it installed successfully!

[This link](https://github.com/nodejs/node-gyp#on-windows) helped me to install Python and VS C++ build tools.
