### ISSUE TITLE
Security issue with handlebars <4.0.0

### ISSUE THREAD

**Issue by miguelusque** [jakearchibald/wittr#29]
Hi all!

It looks like there is a security issue with the _handlebars_ version used in this project.

> The handlebars dependency defined in package.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated.

Could you please have a look at it?

Thanks!!!

Miguel Ángel

**Comment by jakearchibald** [comment]
Hi, this is a demo project and isn't designed to be deployed on an external-facing server, so the issues don't apply here. Happy to take a PR to update the dependency though!

**Comment by miguelusque** [comment]
Hi!

Thank you for your quick answer. I do get your point, but please let me share with you a conversation that I had with my little nephew once:

   - me: Your room is a disaster. You should keep it cleaner and tidier!
   - my little nephew: Why if my friends are not visiting me today?

  Have a great day,

Miguel Ángel
