### ISSUE TITLE
A branch for the latest assignment results

### ISSUE THREAD

**Issue by kkomelin** [jakearchibald/wittr#5]
Hi Jake,

First of all, thank you very much for the course! You have done a really great job! It has made Service Worker much clearer to me. 

The only thing I wanted to know is the name of the branch for the results of the latest assignment? The reason I am wondering is that my final code is not stable in regular version of Chrome for some reason and I wanted to make sure I have done everything right.

Thank you so much in advance,
Konstantin

**Comment by jakearchibald** [comment]
`cache-avatars` is the final branch. Glad you enjoyed the course!

**Comment by kkomelin** [comment]
Thanks @jakearchibald !
