### ISSUE TITLE
Unable to clone projects from github

### ISSUE THREAD

**Issue by codearemo** [jakearchibald/wittr#60]
Please I keep getting this error message every time I run
**git clone https://github.com/jakearchibald/wittr.git**
Please help

fatal: remote did not send all necessary objects
Unlink of file 'wittr/.git/objects/pack/pack-ab460917861de551198a7dcfa162b022b58640d5.idx' failed. Should I try again? (y/n)

- So I tried downloading it
- and I ran git init (that was successful till i had to run)
- **git reset --hard** (this didn't make any prompt...so not sure if it worked)
- **git checkout log-requests** => (fatal: Not a git repository (or any of the parent directories): .git)
and my life went from miserable to more miserable from there... 😞😞
Even chrome Router tab isn't present (may be an update or something removed it).

Please I need to finish this preoject

**Comment by GrandFunkyGamer** [comment]
Try cloning with SSH instead of HTTPS.
