### ISSUE TITLE
Is that bluebar on top is copyright by Google ?

### ISSUE THREAD

**Issue by ghost** [jakearchibald/wittr#62]
That blue navigation bar that I am seeing in top of android and this application look good to me.  Is that copyright by google.

Or I can use it in my code. that blue navigation which is part of PWA.

Thanks in advance,

**Comment by iamchathu** [comment]
It seems it from Material CSS so you use it or use Material CSS

**Comment by ghost** [comment]
ok, you means no copyright issue ?

**Comment by iamchathu** [comment]
For 100% use this one [materializecss](https://materializecss.com/)

**Comment by jakearchibald** [comment]
https://material.io/develop/web/components/top-app-bar/
