### ISSUE TITLE
[Bug] npm run serve produces errors and doesnt start the servers

### ISSUE THREAD

**Issue by Nithanaroy** [jakearchibald/wittr#8]
Here is the debug log which shows the errors on running `npm run serve`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info preserve wittr@1.0.0
6 info serve wittr@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info wittr@1.0.0 Failed to exec serve script
9 verbose stack Error: wittr@1.0.0 serve: `gulp serve`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid wittr@1.0.0
11 verbose cwd /Volumes/350GB/Projects/offline-first-course-app
12 error Darwin 13.4.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error wittr@1.0.0 serve: `gulp serve`
17 error Exit status 1
18 error Failed at the wittr@1.0.0 serve script 'gulp serve'.
18 error This is most likely a problem with the wittr package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp serve
18 error You can get their info via:
18 error     npm owner ls wittr
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by jakearchibald** [comment]
I'm struggling to recreate this. Can you update node & npm and see if you get the same error?

**Comment by Nithanaroy** [comment]
Thanks Jake. After upgrade those errors are fixed. Learned a new thing today.

**Comment by jakearchibald** [comment]
Hah, I wish I knew *why* those errors happened, but at least it's working!

**Comment by arigbs** [comment]
Ran into the same error, and upgrading npm and node has not solved it.

**Comment by Areahints** [comment]
getting the same error using Docker 

`sudo docker-compose up`

```Creating network "wittr_default" with the default driver
Pulling wittr (node:latest)...
latest: Pulling from library/node
3d77ce4481b1: Pull complete
534514c83d69: Pull complete
d562b1c3ac3f: Pull complete
4b85e68dc01d: Pull complete
f6a66c5de9db: Pull complete
7a4e7d9a081d: Pull complete
f5bf9e503c82: Pull complete
2ec8f0a2e902: Pull complete
Digest: sha256:ff6ab53a25af75e309d4b9fed3b3759c747635bad402f7fbe70b7232774a8301
Status: Downloaded newer image for node:latest
Creating c-wittr ... done
Attaching to c-wittr
c-wittr  | 
c-wittr  | > wittr@1.0.0 serve /usr/src/app
c-wittr  | > gulp serve
c-wittr  | 
c-wittr  | internal/modules/cjs/loader.js:596
c-wittr  |     throw err;
c-wittr  |     ^
c-wittr  | 
c-wittr  | Error: Cannot find module 'lodash/object/assign'
c-wittr  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
c-wittr  |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
c-wittr  |     at Module.require (internal/modules/cjs/loader.js:650:17)
c-wittr  |     at require (internal/modules/cjs/helpers.js:20:18)
c-wittr  |     at Object.<anonymous> (/usr/src/app/gulpfile.js:5:14)
c-wittr  |     at Module._compile (internal/modules/cjs/loader.js:702:30)
c-wittr  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
c-wittr  |     at Module.load (internal/modules/cjs/loader.js:612:32)
c-wittr  |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
c-wittr  |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
c-wittr  | npm ERR! code ELIFECYCLE
c-wittr  | npm ERR! errno 1
c-wittr  | npm ERR! wittr@1.0.0 serve: `gulp serve`
c-wittr  | npm ERR! Exit status 1
c-wittr  | npm ERR! 
c-wittr  | npm ERR! Failed at the wittr@1.0.0 serve script.
c-wittr  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
c-wittr  | 
c-wittr  | npm ERR! A complete log of this run can be found in:
c-wittr  | npm ERR!     /root/.npm/_logs/2018-05-28T09_42_02_312Z-debug.log
c-wittr exited with code 1```
